name: mssql-intershop

services:
  mssql-server:
    build: .
    image: mssql-intershop:2019-latest
    container_name: mssql-intershop-2019-latest
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: mssqlserver
        target: /var/opt/mssql
        volume:
          nocopy: true
      - ./backup:/var/opt/mssql/backup
    environment:
      ACCEPT_EULA:  Y
      SA_PASSWORD:  1nstershop5A
      MSSQL_PID:    Developer
      RECREATEDB:   "false"
      RECREATEUSER: "false"
      ICM_DB_NAME:  ish_7_10_dev
    restart: unless-stopped

volumes:
  mssqlserver: